=head1 NAME

MyAgentName - super short description

=head1 DESCRIPTION

(Describe the agent here.  Describe what work it is trying to do, and
generally how it is accomplished.  Avoid quoting specific values such
as cycle times, durations, or file counts which may change in the code
and fall out of sync with the description.)

=head1 TABLES USED

=over

=item L<table_name|PHEDEX::Schema::Section/table_name)>

(Description of how the agent uses the table)

=head1 COOPERATING AGENTS

=over

=item L<(OtherAgentName)|(PHEDEX::OtherAgentName::Agent)>

(Describe how this agent cooperates with the above)

=back

=head1 STATISTICS

=over

=item L<table_name|PHEDEX::Schema::Section/table_name>

(Describe what statistics come from this agent to this table.)

=back

=head1 SEE ALSO

(Make a list of other classes or code that is used by this agent.  No
need to re-list the cooperating agents above.)

=over

=item L<PHEDEX::Core::Agent>

=back

=cut
