# This template is for the perldoc documentation of schema creation
# scripts.  The purpose of the documentation should be to adequately
# describe the data structures, and provide links between data
# structures.

/*

=pod

=head1 NAME

(Name of the category of tables described here.)

=head1 DESCRIPTION

(Description of the category of tables described here.  Describe what
concepts are defined by these data structures, and how they fit in to
the whole application.)

=head1 TABLES

=head2 t_table1

(Describe what this table defines, and what agents (with links!)
create, delete, or modify rows.)

=over

=item t_table1.col1

(Describe what the column means.)

=item t_table1.col2

(Describe what the column means.)

=back

=cut

*/

/* (Now put the table definition) */

create table t_table1 (
  col1    number,
  col2    number
);

/* (Put any associated sequences or indexes below) */
create index ix_table1_col1
  on t_table1 (col1);

/*

=pod

=head2 t_table2

(The next table...)

=over

=item t_table2.col1

(The next tables columns...)

=back

=cut

*/

/* (Now put the table definition) */

create table t_table2 (
  col1    number,
  col2    number
);

/* (Put any associated sequences or indexes below) */
