#!/usr/bin/env perl

##H Minimal fake stager agent for simulations.
##H
##H Usage:
##H   FileFakeStager
##H      -state DIRECTORY -db FILE[:SECTION] [-log OUT]
##H      -nodes PATTERN[,PATTERN...]
##H
##H -state       agent state directory
##H -nodes       the nodes where this agent runs
##H -db          database connection configuration parameter file
##H -log         where to redirect logging information

######################################################################

my %args;
use Getopt::Long;
use PHEDEX::Core::Help;
use PHEDEX::File::FakeStager::Agent;

&GetOptions ("state=s"     => \$args{DROPDIR},
	     "log=s"       => \$args{LOGFILE},
             "db=s"        => \$args{DBCONFIG},
	     "nodes=s"     => sub { push(@{$args{NODES}}, split(/,/, $_[1])) },
	     "help|h"      => sub { &usage() });

if (!$args{DROPDIR} || !$args{DBCONFIG} || !$args{NODES})
{
    die "Insufficient parameters, use -h for help.\n";
}

my $agent = PHEDEX::File::FakeStager::Agent->new(%args,@ARGV);
POE::Kernel->run();
print "POE kernel has ended, now I shoot myself\n";
exit 0;
