#!/bin/sh

dataset= owner= subpath= lfn=
for arg; do
  case $arg in
    pfn=*/cms/PCP04/*) subpath=$(echo $arg | sed 's!.*/\(cms/PCP04/[^/]*\).*!\1!') ;;
    owner=*) owner=$(echo $arg | sed 's![^=]*=!!') ;;
    dataset=*) dataset=$(echo $arg | sed 's![^=]*=!!') ;;
    lfn=*) lfn=$(echo $arg | sed 's![^=]*=!!') ;;
  esac
done

[ -z "$subpath" ] && { echo "no subpath" 1>&2; exit 1; }
[ -z "$owner" ] && { echo "no owner" 1>&2; exit 1; }
[ -z "$dataset" ] && { echo "no dataset" 1>&2; exit 1; }
[ -z "$lfn" ] && { echo "no lfn" 1>&2; exit 1; }
 
# Copy everything into a subdirectories of a local directory.
local=/data/test/files/$subpath/$dataset/$owner/$lfn
mkdir -p $(dirname $local)
echo file:$local
