#! /usr/bin/env perl

##H
##H This agent performs the verification of downloaded blocks.
##H Ask Tony how it works...
##H
##H
##H Usage:
##H   BlockDownloadVerify
##H      -state DIRECTORY -nodes NODE
##H      -db FILE[:SECTION] [-log OUT]
##H      -storagemap TFC.xml
##H
##H -state         agent state directory.
##H -nodes         nodes to run and check files for.
##H -db            database connection configuration parameter file.
##H -log           where to redirect logging information.
##H -storagemap    path to TFC xml file
##H

my $debug_me = 1;

######################################################################
use Getopt::Long;
use PHEDEX::Core::Help;
use PHEDEX::BlockConsistency::Agent;

&GetOptions ("state=s"      => \$args{DROPDIR},
	     "log=s"        => \$args{LOGFILE},
	     "db=s"         => \$args{DBCONFIG},
	     "storagemap=s" => \$args{STORAGEMAP},
             "nodes=s"      => sub { push(@{$args{NODES}}, split(/,/, $_[1])) },
             "ignore=s"     => sub { push(@{$args{IGNORE_NODES}}, split(/,/, $_[1])) },
             "accept=s"     => sub { push(@{$args{ACCEPT_NODES}}, split(/,/, $_[1])) },
	     "help|h"	    => sub { &usage() },
	     "use_srm"      => \$args{USE_SRM},
	     "use_rfdir"    => \$args{RFIO_USES_RFDIR},
	    );

if (!$args{DROPDIR} || !$args{NODES} || !$args{DBCONFIG} || !$args{STORAGEMAP})
{
    die "Insufficient parameters, use -h for help.\n";
}
$args{LOGFILE} = $args{DROPDIR} . '/log.txt' unless defined $args{LOGFILE};

(new PHEDEX::BlockConsistency::Agent (%args, @ARGV))->process();
