#!/bin/bash
#
# cmsweb_phedex : starts / stops PhEDEx mod_perl based backend services

if [ -z ${PHEDEX_WEB_HOME} ]; then
   echo $"The PHEDEX_WEB_HOME environment is not set"
   exit 1
fi
cd ${PHEDEX_WEB_HOME}

RETVAL=$?

pid=`ps -p $(cat ./apache2-conf/logs/httpd.pid 2>/dev/null) -o pid= 2> /dev/null`
cmd="./apache2-conf/bin/httpd -k "
name="PhEDEx web services"

case "$1" in
 restart)
        if [ ! -z ${pid} ]; then
	    echo $"Graceful restart of ${name}..."
	    ${cmd} graceful 2>&1 1>& /dev/null < /dev/null &
	    exit 0
        else
	    echo $"${name} were not running, will start..."
	    ${cmd} start 2>&1 1>& /dev/null < /dev/null &
	    exit 0
	fi
	;;
 start)
	echo $"Starting ${name}..."
        ${cmd} start 2>&1 1>& /dev/null < /dev/null &
	;;
 status)
	echo $"Checking ${name}..."
        if [ ! -z ${pid} ]; then
          echo $"${name} are running, pid=${pid}"
          exit 0
        fi
        echo $"${name} are stopped"
        exit 3
	;;
 stop)
	echo $"Stopping ${name}..."
        if [ ! -z ${pid} ]; then
	    ${cmd} stop 2>&1 1>& /dev/null < /dev/null &
        fi
 	;;
 *)
 	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
	;;
esac

exit $RETVAL
