#!/usr/bin/env perl

=head1 NAME

Service - Main program of the PhEDEx data service

=head1 DESCRIPTION

Checks configuration, parses URL path for parameters, makes API call, all
done via the DataService module.

=cut

use warnings;
use strict;

use PHEDEX::Web::DataService;
my $service = PHEDEX::Web::DataService->new();
$service->init_security();
$service->invoke();
