#!/usr/bin/env perl
use POSIX;

##H Usage: DoNothing [MIN-TIME [MAX-TIME [...]]]
##H
##H Sleeps for a random time between MIN-TIME and MAX-TIME in seconds.
##H By default MIN-TIME is 30 seconds, and MAX-TIME is MIN-TIME + 30.

my $min = shift(@ARGV) || 30;
my $max = shift(@ARGV) || ($min + 30);
select(undef, undef, undef, $min + rand($max - $min));
exit (0);
