#!/bin/sh

# A script for starting the graphtool configured for PhEDEx

sw=  # set to software area
export GRAPHTOOL_CONFIG_ROOT= # set to config location
export PHEDEX_DBPARAM= # set to DBParam location

# Necessary libs
source $sw/cms/webtools/1.3.3-cmp/etc/profile.d/init.sh
source $sw/external/py2-matplotlib/0.90.1-cmp/etc/profile.d/init.sh
source $sw/external/py2-numpy/1.0.1-cmp/etc/profile.d/init.sh
source $sw/external/libjpg/6b-cmp/etc/profile.d/init.sh

# Path hacks
export PYTHONPATH=$sw/external/py2-pil/1.1.6-cmp/lib/python2.4/site-packages/PIL:$PYTHONPATH
export GRAPHTOOL_ROOT=$sw/cms/webtools/1.3.3-cmp/lib/python2.4/site-packages/Tools/GraphTool
export PYTHONPATH=$GRAPHTOOL_ROOT/src:$PYTHONPATH
export PYTHONPATH=$GRAPHTOOL_CONFIG_ROOT/src:$PYTHONPATH

echo $PYTHONPATH;
python $GRAPHTOOL_CONFIG_ROOT/tools/phedex-web-daemon.py
