#!/usr/bin/env perl

##H Check connectivity to TMDB from a DBParam file.
##H
##H Usage:
##H   CheckDBConnection -db FILE[:SECTION]
##H
##H returns zero if the connection succeeds, or prints the error and quits with a non-zero value

# Process command line arguments.
my %args;
use Getopt::Long;
use PHEDEX::Core::Help;
use PHEDEX::Core::DB;
&GetOptions ("db=s"        => \$args{DBCONFIG},
	     "help|h"      => sub { &usage() });

# Check arguments.
if (@ARGV || !$args{DBCONFIG})
{
    die "Insufficient parameters, use -h for help.\n";
}

my $h = { DBCONFIG => $args{DBCONFIG} };
eval {
  connectToDatabase($h);
  disconnectFromDatabase($h,$h->{DBH},1);
};
if ( $@ )
{
  print $@;
  exit 1;
}
print "Connection to TMDB with ",$args{DBCONFIG}," succeeded\n";
exit 0;

