#!/usr/bin/env perl

##H Dump tables from database
##H
##H Usage:
##H   DBDump -db FILE[:SECTION] } TABLE...
##H
##H -db           database connection configuration parameter file
##H TABLE         name of the table to dump

my %args;
use Getopt::Long;
use PHEDEX::Core::Help;
use PHEDEX::Core::DB;
&GetOptions ("db=s"        => \$args{DBCONFIG},
	     "help|h"      => sub { &usage() });

if (! $args{DBCONFIG})
{
    die "Insufficient parameters, use -h for help.\n";
}

my $dbh = &connectToDatabase (\%args);
foreach my $table (@ARGV)
{
    my $q = &dbexec ($dbh, qq{select * from $table});
    my $nrows = 0;
    while (my $row = $q->fetchrow_hashref())
    {
	print "$table,", ++$nrows;
	foreach my $k (sort keys %$row)
	{
	    my $v = $row->{$k};
	    print defined $v ? ",$k,\"$v\"" : ",$k,";
	}
	print "\n";
    }
}

&disconnectFromDatabase(\%args, $dbh, 1);
