#!/usr/bin/env perl

##H Dump tables from database
##H
##H Usage:
##H   DSBDump -db FILE[:SECTION] } TABLE...
##H
##H -db           database connection configuration parameter file
##H TABLE         name of the table to dump

BEGIN { use strict; use warnings; $^W=1;
  my $me = $0; $me =~ s|.*/||;
  my $home = $0; $home =~ s|/[^/]+$||; $home ||= ".";
  unshift(@INC, "$home/../Toolkit/Common"); }
use UtilsHelp;
use UtilsDB;

while (scalar @ARGV)
{
    if ($ARGV[0] eq '-h') {
	&usage();
    } elsif ($ARGV[0] eq '-db' && scalar @ARGV > 1) {
	shift (@ARGV); $args{DBCONFIG} = shift (@ARGV);
    } elsif ($ARGV[0] eq '--') {
	shift (@ARGV); last;
    } elsif ($ARGV[0] =~ '^-') {
	&usage ("$0: unrecognised option $ARGV[0]\n\n");
    } else {
	last;
    }
}

if (! $args{DBCONFIG})
{
    die "Insufficient parameters, use -h for help.\n";
}

my $dbh = &connectToDatabase (\%args, 0);
foreach my $table (@ARGV)
{
    my $q = &dbexec ($dbh, qq{select * from $table});
    my $nrows = 0;
    while (my $row = $q->fetchrow_hashref())
    {
	print "$table,", ++$nrows;
	foreach my $k (sort keys %$row)
	{
	    my $v = $row->{$k};
	    print ",$k,\"$v\"";
	}
	print "\n";
    }
}

$dbh->disconnect();
