#!/usr/bin/perl

BEGIN { use strict; use warnings; }

sub report
{
    my ($prefix, $dir) = @_;
    my %drops = ();
    my $inbox = 0;
    my $received = 0;
    my $pending = 0;
    my $bad = 0;
    my $done = 0;
    my $outbox = 0;
    foreach my $d (<$dir/{inbox,work,outbox}/*>) {
	my @files = <$d/{go,bad,done}>;
	$inbox++ if $d =~ m|/inbox/|;
	$received++ if $d =~ m|/inbox/| && grep (m|/go$|, @files);
	$pending++  if $d =~ m|/work/|;
	$bad++ if $d =~ m|/work/| && grep (m|/bad$|, @files);
	$done++ if $d =~ m|/work/| && grep (m|/done$|, @files);
	$outbox++ if $d =~ m|/outbox/|;
    }
    print "$prefix:",
	" @{[$inbox - $received]} pending,",
	" $received received,",
	" @{[$pending - $bad - $done]} work,",
	" $done completed,",
	" $bad bad,",
	" $outbox outgoing\n";
}

foreach $dropdir (@ARGV)
{
    print "$dropdir: \n";
    foreach $w (<$dropdir/worker-*>)
    {
	my $id = ($w =~ /worker-(\d+)/)[0];
	&report (" W$id", $w);
    }

    &report ("  M", $dropdir);
}
