#!/usr/bin/env perl

BEGIN { use strict; use warnings; $^W=1; }

sub report
{
    my ($prefix, $dir) = @_;
    my %drops = ();
    my $inbox = 0;
    my $received = 0;
    my $pending = 0;
    my $bad = 0;
    my $done = 0;
    my $outbox = 0;

    foreach my $d (<$dir/inbox/*>) {
	$inbox++;
	$received++ if -f "$d/go";
    }

    foreach my $d (<$dir/work/*>) {
	$pending++;
	$bad++ if -f "$d/bad";
	$done++ if -f "$d/done";
    }

    foreach my $d (<$dir/outbox/*>) {
	$outbox++;
    }

    print "$prefix:",
	" @{[$inbox - $received]} pending,",
	" $received received,",
	" @{[$pending - $bad - $done]} work,",
	" $done completed,",
	" $bad bad,",
	" $outbox outgoing\n";
}

foreach $dropdir (@ARGV)
{
    print "$dropdir: \n";
    foreach $w (<$dropdir/worker-*>)
    {
	my $id = ($w =~ /worker-(\d+)/)[0];
	&report (" W$id", $w);
    }

    &report ("  M", $dropdir);
}
