#!/usr/bin/env python
from PyFileCatalog import *
from PyFCContainer import *
from PyFCAction import *
import os,os.path,getopt

def usage():
    print 'FCmergeMeta -u catalog_contactstring meta-file...'

class myobj(object):
    def __init__(self):
        self.input=[]
	self.inputdata=[]
	self.cat = None
        try:
            optlist,self.input = getopt.getopt (sys.argv[1:],'u:')
        except getopt.GetoptError:
            usage()
            sys.exit(2)
        for o,a in optlist:
            if o == '-u':
                self.cat = a
            else:
                usage()
                sys.exit(2)

	if self.cat == None:
	    usage()
	    sys.exit(2)

        try:
            self.x=PyFileCatalog.PyFileCatalog()
            self.x.setWriteCatalog(self.cat)
        except PyFileCatalogError, er:
            print >> sys.stderr, 'File catalogue error:', er
            self.x.rollback()

    def read(self,filename):
        for line in open(filename):
            self.inputdata.append(line)

    def parse(self,str):
	import re
	pos = 0
	items = {}
	rx = re.compile(r'\(([^,]+),(.*?)\),?');
	while True:
	    m = rx.match(str, pos)
	    if m == None: break
	    items [m.group(1)] = m.group(2)
	    pos = m.end(0)

	return items

    def upload(self):
        try:
            self.x.setAction(PyFCregister())
            self.x.connect()
            self.x.start()
            for entry in self.inputdata:
                metadatadict=self.parse(entry)
                print metadatadict['guid']
                self.x.wchild.insertMetaData(metadatadict['guid'],metadatadict)
            self.x.commit(REFRESH)
	    self.x.disconnect()
        except PyFileCatalogError, er:
            print >> sys.stderr, 'File catalogue error:', er
            self.x.rollback()
        except Exception, er:
            print >> sys.stderr, 'An error:', er
            self.x.rollback()

if __name__=="__main__":
    y=myobj()
    for file in y.input:
	y.read(file)
    y.upload()
