#!/usr/bin/env perl

use strict; $^W=1;

my ($dir,$surlroot) = @ARGV;

# This script takes a Castor directory, and returns a list of directories
# and SURLs
print "nsls -l $dir\n";
open( NSLS, "nsls -l $dir |" );
while( <NSLS> ) {
    if ( ! /^total/ ) {
	my ( $mode,$stuff,$user,$group,$size,$month,$day,$time,$file ) = split( /\s+/ );
	if ( $mode =~ /^d/ ) {
	    print "d: $file\n";
	} else {
	    my $surl = $surlroot."$dir$file";
	    print "$surl\n";
	}
    }
}
close( NSLS );
