#!/bin/sh

##H Generate transfer rate statistics for report card.
##H
##H Usage:
##H   MakeAllStats -db FILE
##H
##H -db   database connection configuration parameter file

for db in Production SC3 Dev; do
  addopt=
  if [ $db = Production ]; then
    addopt="-add $(dirname $0)/../Documentation/DailyStatsDiff.txt"
    addopt="$addopt -add $(dirname $0)/../Documentation/DailyStatsFZKDiff.txt"
  fi
  $(dirname $0)/MakeDailyStats $1 $2:$db/Admin $(echo $addopt) -output $db-
done
