#!/usr/bin/env perl

# This Master script is used to startup agents in a well-defined
# environment. The environment is defined by one or more configuration
# files. These configuration files have a specific format, but typically
# have one of two types of section- denoted either ENVIRON, in which
# environment variables are set, or AGENT, in which a particular agent
# instance is defined, indicating executable and command line arguments.
#
# Usage
#
# Master -config <Config file>[,<Config file>,...]  MODE AGENT|all

# First we need to parse the command line arguments
BEGIN { use warnings; use strict; }

while (@ARGV)
{
    if ($ARGV[0] eq "-config" && scalar @ARGV > 1) 	
    { shift (@ARGV); push (@{$args{CONFIG}}, split(/,/, shift(@ARGV))); }
    elsif ($ARGV[0] =~ /^-/) 
    { die "TestMaster- unrecognised option $ARGV[0]\n"; } 
    else { last; }
}

my $mode = shift(@ARGV) || "start";

if (!$args{CONFIG} ) { 
    die "Sorry, you need to specify a config file\n"; 
}

# Then set variables at script scope...
my @configuration = ();
my $environ = '';
my %environs = ();
my @agents = ();

# Then we need to open up each of the config files
foreach my $file ( @{$args{CONFIG}} ) {
    -f $file || die "$file: no such file\n";
    -r $file || die "$file: not readable\n";

    open(CONFIG, "< $file") || die "$file: cannot read: $!\n";
    while (<CONFIG>) {
	while (/^\#\#\#\s+([A-Z]+)(\s+(.*)|$)/) {
	    chomp; 
	    s/\s+$//;
	    
	    # Here we process ENVIRON sections, defined as follows:
	    # ### ENVIRON [optional label]
	    if ($1 eq "ENVIRON")
	    {
		chomp;
		my @tags = split( / / );
		my $label = '';
		if ( $tags[2] =~ /[a-z]/)
		{
		    $label = $tags[2];
		    $label =~ s/\s//;
		} else {
		    $label = "generic";
		    if ( defined $environs{$label} )
		    {
			print "# You have multiple environs without labels- they will be run together!\n";
		    } 
		}
		while (<CONFIG>)
		{
		    last if /^###/; chomp; s/#.*//; s/^\s+//; s/\s+$//;
		    $environs{$label} .= "$_\n" if ($_ ne "");
		}
	    }

	    # Here we process AGENT sections, defined as follows:
	    # ### AGENT LABEL=<label> PROGRAM=<executable> [ENVIRON=<label>
	    elsif ($1 eq "AGENT")
	    {
		my $agent = { map { m|([^=]+)=(\S+)|g } split(/\s+/, $3) };
		push( @agents, $agent );
		while (<CONFIG>)
		{
		    last if /^###/; chomp; s/#.*//; s/^\s+//; s/\s+$//;
		    $agent->{OPTS} .= " $_" if ($_ ne "");
		}
	    }
	    else
	    {
		die "unrecognised section $1\n";
	    }
	}
    }
	       
    close (CONFIG);

}
    
# And finally act on all this information
if ($mode eq "start" || $mode eq "stop" || $mode eq 'show')
{
    foreach $agent (@agents) {
	next if (@ARGV && !grep($_ eq "all" || $_ eq $agent->{LABEL}, @ARGV));
	next if (! @ARGV && ($agent->{DEFAULT} || 'on') eq 'off');
	next if (! @ARGV); # without agent name or all, nothing is started

	if ($mode eq 'show') {
	    open (SH, ">&STDOUT") or die "cannot open output: $!\n";
	} else {
	    open (SH, "| sh") or die "cannot exec sh: $!\n";
	}
	
	print SH "\n#\n# Environment and startup for agent $agent->{LABEL}\n#\n";

	# Here we need to work out which environment each agent needs, make sure
	# it's been defined and if so, source it. Skip agents with wierd or undecidable
	# environment requirements
        if ( defined $environs{"common"} )
        {
            print SH $environs{"common"}, "\n";
        }
	if ( ! defined $agent->{ENVIRON} )
	{
	    if ( ! defined $environs{"generic"} )
	    {
		print "# Agent $agent->{LABEL} doesn't specify an environment, and no generic environment is set, not starting\n";
		next;
	    } else {
		print SH $environs{"generic"}, "\n";
	    }
	} elsif ( ! exists $environs{$agent->{ENVIRON}} ) {
	    print "# Agent $agent->{LABEL} specifies an environment that doesn't exist, not starting\n";
	    next;
	} else {
	    print SH $environs{$agent->{ENVIRON}},"\n";
	}
	    
	# Now actually act on the mode, and start or show agents
	if ($mode eq 'start' || $mode eq 'show') {
	    print SH "mkdir -p \${PHEDEX_STATE}/$agent->{LABEL} &&",
	    " mkdir -p \${PHEDEX_LOGS} &&",
	    ($agent->{STATELINK}
	     ? " ln -sf $agent->{LABEL} \${PHEDEX_STATE}/$agent->{STATELINK};" : " :;"),
	    "\nnohup \${PHEDEX_SCRIPTS}/$agent->{PROGRAM}",
	    (" -", $agent->{STATEOPT} || "state", " ", "\${PHEDEX_STATE}/$agent->{LABEL}"),
	    $agent->{OPTS},
	    " >> \${PHEDEX_LOGS}/$agent->{LABEL} 2>&1 </dev/null &\n";
	} elsif ($mode eq 'stop') {
	    print SH "touch \${PHEDEX_STATE}/$agent->{LABEL}/stop\n";
	}
	close(SH);
    }
}
elsif ($mode eq "environ")
{
    if (! @ARGV) 
    {
	print "# Writing out all environments\n";
	foreach my $label ( keys %environs ) {
	    print "# Environment: $label\n";
	    print "$environs{$label}\n";
	}
    } else {
	foreach my $label ( @ARGV ) 
	{
	    print "# Environment: $label\n";
	    print "$environs{$label}\n";
	}
    }
}
else
{
    die "unrecognised operation mode \"$mode\"\n";
}

