#!/bin/sh

for rename; do
  old=$(echo $rename | sed 's/:.*//')
  new=$(echo $rename | sed 's/.*://')
  echo "insert into t_node values ('$new');"
  echo "update t_node_import set node = '$new' where node = '$old';"
  echo "update t_node_export set node = '$new' where node = '$old';"
  echo "update t_subscription set destination = '$new' where destination = '$old';"
  echo "update t_routing set from_node = '$new' where from_node = '$old';"
  echo "update t_routing set to_node = '$new' where to_node = '$old';"
  echo "update t_routing set gateway = '$new' where gateway = '$old';"
  echo "update t_destination set node = '$new' where node = '$old';"
  echo "update t_file set node = '$new' where node = '$old';"
  echo "update t_replica_state set node = '$new' where node = '$old';"
  echo "update t_block_replica set node = '$new' where node = '$old';"
  echo "update t_transfer_state set to_node = '$new' where to_node = '$old';"
  echo "update t_transfer_state set from_node = '$new' where from_node = '$old';"
  echo "update t_transfer_completed set to_node = '$new' where to_node = '$old';"
  echo "update t_transfer_completed set from_node = '$new' where from_node = '$old';"
  echo "update t_transfer_history set to_node = '$new' where to_node = '$old';"
  echo "update t_transfer_history set from_node = '$new' where from_node = '$old';"
  echo "update t_transfer_summary set to_node = '$new' where to_node = '$old';"
  echo "update t_transfer_summary set from_node = '$new' where from_node = '$old';"
  echo "update t_perf_histogram set to_node = '$new' where to_node = '$old';"
  echo "update t_perf_histogram set from_node = '$new' where from_node = '$old';"
  echo "update t_agent_status set node = '$new' where node = '$old';"
  echo "delete from t_node where name = '$old';"
  echo "commit;"
done
