#!/usr/bin/env perl

##H Generate Oracle SQL*Plus connect identifier from DBParam file.
##H
##H Usage:
##H   OracleConnectId -db FILE[:SECTION]

# Process command line arguments.
my %args;
use Getopt::Long;
use PHEDEX::Core::Help;
use PHEDEX::Core::DB;
&GetOptions ("db=s"        => \$args{DBCONFIG},
	     "help|h"      => sub { &usage() });

# Check arguments.
if (@ARGV || !$args{DBCONFIG})
{
    die "Insufficient parameters, use -h for help.\n";
}

&parseDatabaseInfo (\%args);
print "$args{DBH_DBUSER}/$args{DBH_DBPASS}\@$args{DBH_DBNAME}\n";
