#!/usr/bin/env perl

BEGIN { use strict; use warnings; $^W=1;
  my $me = $0; $me =~ s|.*/||;
  my $home = $0; $home =~ s|/[^/]+$||; $home ||= ".";
  unshift(@INC, "$home/../Toolkit/Common"); }
use UtilsTR;

$verbose = 0;
if ($ARGV[0] eq '-v') {
    $verbose = 1; shift (@ARGV);
}

foreach my $dso (@ARGV) {
    my ($o, $ds) = ($dso =~ /(.*)\/(.*)/);
    my @assids = &listAssignments ({ DATASET => $ds, OWNER => $o });
    print "@assids", ($verbose ? " $o/$ds" : ""), "\n"
	if @assids;
}
