#!/usr/bin/env perl

BEGIN { use strict; use warnings; $^W=1;
  my $me = $0; $me =~ s|.*/||;
  my $home = $0; $home =~ s|/[^/]+$||; $home ||= ".";
  unshift(@INC, "$home/../Toolkit/Common"); }
use UtilsTR;

print map { "$_->{OWNER}/$_->{DATASET}\n" } &listDatasetOwners (&readPatterns (@ARGV));
