#!/usr/bin/env perl

##H See or Remove the router suspension for blocks at a node
##H
##H Usage:
##H   RouterSuspend -db DBCONFIG [-node NODE] [-block BLOCK] [-unsuspend]
##H
##H By default displays all block destinations which were suspended by
##H the router due to constant failures, with optional filters.  By
##H adding the -unsuspend flag, block destinations matching the query
##H are unsuspended.
##H
##H Options:
##H   -node NODE        Node to filter results by
##H   -block BLOCK      Block to filter results by, accepts SQL wildcards (%)
##H   -unsuspend        Unsuspend the matching block destinations

# Process command line arguments.
my %args;
use Getopt::Long;
use PHEDEX::Core::Help;
use PHEDEX::Core::DB;
use PHEDEX::Core::Timing;
&GetOptions ("db=s"            => \$args{DBCONFIG},
	     "node=s"          => \$args{NODE},
	     "block=s"         => \$args{BLOCK},
	     "unsuspend"       => \$args{UNSUSPEND},
	     "help|h"          => sub { &usage() });

if (!$args{DBCONFIG})
{
    die "Insufficient parameters, use -h for help.\n";
}

my $self = { DBCONFIG => $args{DBCONFIG} };
my $dbh = &connectToDatabase ($self);
my $now = &mytimeofday();

my $where = '';
my %p;
if ($args{NODE}) {
    $where .= " and n.name = :node";
    $p{NODE} = $args{NODE};
}
if ($args{BLOCK}) {
    $where .= " and b.name like :block";
    $p{BLOCK} = $args{BLOCK};
}

if (!$args{UNSUSPEND}) {
    my $q = &dbexec($dbh, qq{
       select n.name node, b.name block, b.files, b.bytes / power(1024,3) size_gb,
              bd.time_subscription, bd.time_active, bd.time_suspend_until 
         from t_dps_block_dest bd 
         join t_adm_node n 
           on n.id = bd.destination 
         join t_dps_block b 
           on b.id = bd.block 
        where bd.state = 4 $where
     order by n.name, bd.time_subscription, bd.time_active
    }, %p);

    printf("%20s %40s %6s %5s %6s %6s %6s\n", 
	   qw(node block files size_gb t_subs t_actv t_susp));
    while (my $row = $q->fetchrow_hashref()) {
	printf("%20s %40s %6i %0.3f %6s %6s %6s\n",
	       $$row{NODE}, $$row{BLOCK}, $$row{FILES}, $$row{SIZE_GB},
	       &age($now-$time_subscription),
	       &age($now-$time_active),
	       &age($now-$time_suspend_until));
    }
} else {
    my ($q, $n) = &dbexec($dbh, qq{
       update t_dps_block_dest
          set state = 0,
              time_suspend_until = NULL
        where (node, block) 
           in ( select bd.node, bd.block
                  from t_dps_block_dest bd 
                  join t_adm_node n 
                    on n.id = bd.destination 
                  join t_dps_block b 
                    on b.id = bd.block 
                 where bd.state = 4 $where
              )}, %p);
    print "$n blocks unsuspended for node=$args{NODE}, block=$args{BLOCK}\n";
    $dbh->commit();
}

&disconnectFromDatabase($self, $dbh, 1);
