#!/bin/sh

# Split the info per job into XML fragments we can re-process
for f; do
  (echo '<?xml version="1.0" encoding="UTF-8" standalone="no" ?>'
   echo '<!DOCTYPE POOLFILECATALOG SYSTEM "InMemory">'
   echo '<POOLFILECATALOG>'
   echo '  <META name="Content" type="string"/>'
   echo '  <META name="DBoid" type="string"/>'
   echo '  <META name="DataType" type="string"/>'
   echo '  <META name="FileCategory" type="string"/>'
   echo '  <META name="Flags" type="string"/>'
   echo '  <META name="dataset" type="string"/>'
   echo '  <META name="jobid" type="string"/>'
   echo '  <META name="owner" type="string"/>'
   echo '  <META name="runid" type="string"/>'
   grep -v -e '^[0-9][0-9]*a$' -e '^\.$' < "$f"
   echo '</POOLFILECATALOG>') > "$f".new
   mv "$f".new "$f"
done
