#!/usr/bin/env perl

##H Produce "dot" graph from the transfer topology.
##H
##H USAGE: UtilTopologyGraph -dbconfig FILE

BEGIN {
  use strict; use warnings;
  our $me = $0; $me =~ s|.*/||;
  our $home = $0; $home =~ s|/[^/]+$||; $home ||= "."; $home .= "/../Toolkit/Common";
  unshift(@INC, $home); }
use UtilsHelp;
use UtilsDB;

my %args;
while (scalar @ARGV)
{
    if ($ARGV[0] eq '-h') {
	&usage ();
    } elsif ($ARGV[0] eq '-dbconfig' && scalar @ARGV > 1) {
	shift (@ARGV); $args{DBCONFIG} = shift(@ARGV);
    } elsif ($ARGV[0] eq '--') {
	shift (@ARGV); last;
    } elsif ($ARGV[0] =~ '^-') {
	&usage ("$0: unrecognised option $ARGV[0]\n\n");
    } else {
	last;
    }
}

if (@ARGV || !$args{UNIT} || !$args{TIME} || !$args{DBCONFIG})
{
    die "Incorrect parameters, use -h for help.\n";
}

my $dbh = &connectToDatabase (\%args, 0);
my $nodes = $dbh->selectall_arrayref(qq{
		select from_node, gateway from t_routing
		where to_node = gateway});

print "digraph routing {\n",
      "  fontname=\"Helvetica\"; fontsize=12; center=true; ratio=compress; concentrate=true;\n",
      "  label=\"\\nPhEDEx Routing Table\\n\"\n\n",
      "  node [shape=ellipse, fontname=\"Helvetica-Bold\", fontsize=12 ]\n",
      "  edge [fontname=\"Helvetica\", fontsize=12 ]\n\n",
      (map { "  \"$_->[0]\" -> \"$_->[1]\" []\n" } @$nodes),
      "}\n";
