#!/bin/sh

grep expiring ${1-MergeTest/logs/merge} |
  awk '{printf "%s\t%s\t%s\t%s\n", $6,$9,$12,$14}' |
  sort |
  sed 's/\.[0-9]*\.[0-9]*\t/\t/; s/^EVD\.//' |
  perl -e '
    while (<STDIN>) {
      ($name, $age, $size, $n) = m|(\S+)|g;
      $streams{$name} ||= { AGE => 0, SIZE => 0, N => 0, COUNT => 0 };
      $streams{$name}{AGE} += $age;
      $streams{$name}{SIZE} += $size;
      $streams{$name}{N} += $n;
      $streams{$name}{COUNT}++;
    }
    while (($k, $v) = each %streams) {
      print sprintf("%s\t%d\t%d\t%.2f\t%.2f\t%.2f\n",
      		    $k, $v->{COUNT}, $v->{N},
		    $v->{AGE}/$v->{COUNT},
		    $v->{SIZE}/$v->{COUNT},
		    $v->{N}/$v->{COUNT});
    }' |
  sort > funnel-stats-1.txt

grep state: ${1-MergeTest/logs/merge} |
  awk '{print $6,$5,$7}' |
  sort -r |
  perl -e '
    $n = undef;
    $start = undef;
    while (<STDIN>) {
      @x = split(/\s+/, $_);
      if ($x[1] eq "start") {
        $n = $x[0]; $start = $x[2];
      } elsif ($x[1] eq "end") {
        print "$n ", ($x[2] - $start), "\n";
      }
    }' > funnel-stats-2.txt
