#!/bin/sh

##H This script installs all Perl modules required by PhEDEx that
##H are not installed on all systems we support.  It doesn't check
##H whether you have the module installed already or not, it simply
##H builds it; most of these modules are trivial and there are too
##H many buggy versions to figure out what works and what doesn't.
##H
##H You are expected to have installed Oracle client libraries on
##H your system already.  See "InstallOraclieClient" for details.
##H
##H The script leaves behind an environment configurations cript
##H you can source to get a fully functional execution environment.
##H
##H Usage: InstallPerlModules DESTINATION
##H
##H DESTINATION is the directory under which you want to install the
##H perl modules.  Typically this is the same destination you give to
##H the other "Install" deployment tools.

# Check command line arguments
if [ $# -ne 1 ]; then
  grep '^##H' $0 | sed 's/^##H\( \|\)//'
  exit 1
fi

destdir="$1"
[ -d "$destdir" ] || { echo "$destdir: not a directory" 1>&2; exit 1; }

# If there is environment setup script there, source it
[ -f "$destdir"/oraenv.sh ] && . "$destdir"/oraenv.sh
[ -z "$ORACLE_HOME" ] && { echo "\$ORACLE_HOME not set" 1>&2; exit 1; }

# Create destination directory for modules.  Figure out all the places
# where perl makefiles stuff the modules into.  This is rather complex.
prefix="$destdir/perl-modules"
version=$(perl -e 'use Config; print $Config{version}')
iprefix=$(perl -e 'use Config; print $Config{installprefixexp}')
sitearch=$(perl -e 'use Config; print $Config{installsitearch}' | sed "s!^$iprefix/*!$prefix/!")
sitelib=$(perl -e 'use Config; print $Config{installsitelib}' | sed "s!^$iprefix/*!$prefix/!")
perlarch=$(perl -e 'use Config; print $Config{installarchlib}' | sed "s!^$iprefix/*!$prefix/!")
perllib=$(perl -e 'use Config; print $Config{installprivlib}' | sed "s!^$iprefix/*!$prefix/!")
PERL5LIB="$sitearch:$sitelib:$perlarch:$perllib:$PERL5LIB"; export PERL5LIB
echo "*** building perl modules for version $version into $prefix, directories are:"
echo "***   $sitearch"
echo "***   $sitelib"
echo "***   $perlarch"
echo "***   $perllib"

mkdir -p "$prefix" || exit $?

# Build basic modules
tmpdir="$destdir/perl-modules-build"
rm -fr "$tmpdir" || exit $?
mkdir -p "$tmpdir" || exit $?
LC_ALL=C; export LC_ALL
for module in http://search.cpan.org/CPAN/authors/id/J/JH/JHI/Time-HiRes-1.66.tar.gz \
	      http://search.cpan.org/CPAN/authors/id/M/MS/MSCHWERN/Test-Simple-0.51.tar.gz \
	      http://search.cpan.org/CPAN/authors/id/T/TI/TIMB/DBI-1.46.tar.gz; do
  moduletar=$(basename $module)
  moduledir=$(basename $moduletar .tar.gz)
  echo; echo "*** building perl module $moduledir"
  (cd $tmpdir || exit $?
   wget -q $module || exit $?
   tar zxf $moduletar || exit $?
   cd $moduledir || exit $?
   perl Makefile.PL prefix="$prefix" || exit $?
   make && make install) || exit $?
done

# Build DBD::Oracle with instant client libraries
for module in http://search.cpan.org/CPAN/authors/id/T/TI/TIMB/DBD-Oracle-1.16.tar.gz; do
  moduletar=$(basename $module)
  moduledir=$(basename $moduletar .tar.gz)
  echo; echo "*** building perl module $moduledir"
  (cd $tmpdir || exit $?
   wget -q $module || exit $?
   tar zxf $moduletar || exit $?
   cd $moduledir || exit $?
   patch Makefile.PL << \EOF
diff Makefile.PL.orig Makefile.PL
1254a1255
>        "$OH/include", # Tim Barrass, hacked for OIC install from zips
EOF
   [ $(uname) = Darwin ] &&
      perl -p -i -e 's/NMEDIT = nmedit/NMEDIT = true/' Makefile.PL
   perl Makefile.PL prefix="$prefix" -l -m $ORACLE_HOME/demo/demo.mk || exit $?
   make && make install) || exit $?
done

rm -fr "$tmpdir"

# Finally, generate required environment setup
echo "PERL5LIB=$sitearch:$sitelib:$perlarch:$perllib\${PERL5LIB+\"\$PERL5LIB\"}; export PERL5LIB;" > "$destdir/perlenv.sh" || exit $?
