#!/usr/bin/env perl

use strict;
use warnings;
use CGI qw(:standard);
use CGI::Carp qw(fatalsToBrowser);
use POSIX;

my $cgi = new CGI;

# ###############################################
# Main loop
# ###############################################

intro();
end();

# ###############################################
# Subroutines
# ###############################################
sub intro
{
    $| = 1;

    my $stamp = strftime ("%Y-%m-%d %H:%M:%S %Z", localtime(time()));
    print $cgi->header();

    print $cgi->start_form(-method=>'POST');

    print "
        <head>
        <title>PhEDEx monitoring</title>
        <meta http-equiv=\"refresh\" content=\"5\">
        </head>
        <body>
        <h1>PhEDEx Monitoring</h1>
        <p>$stamp
        <select name=page>
       	<option value='main'>Front page</option>
       	<option value='transfer'>Transfer state</option>
       	<option value='replicas'>Replica state</option>
       	<option value='subs'>Subscriptions</option>
       	<option value='stats'>File size stats</option>
       	<option value='rates'>Transfer rate</option>
       	<option value='agents'>Agent status</option>
       	</select>
       	<submit>
    ";
    if ($cgi->param('page')) { print $cgi->param('page'); }
}

sub end
{
    print "</body></html>";
}