#!/usr/bin/env perl

BEGIN { use strict; use warnings; $^W=1; }
use CGI qw(param header);

print header(-type=>'text/plain'),
  "Environment:\n",
  (map { "$_ = $ENV{$_}\n" } sort keys %ENV), "\n",

  "Parameters:\n",
  (map { "$_ = @{[param($_)]}\n" } param());

print "base_url: @{[&baseurl()]}\n";
print "root_url: @{[&rooturl()]}\n";
print "root_dir: @{[&urlroot()]}\n";
exit(0);

sub baseurl
{
  my %args = @_;
  my $newcgi = new CGI ("");
  $newcgi->param ($_, $args{$_}) for keys %args;
  return $newcgi->self_url(-full=>0, -relative=>1);
}

sub rooturl
{
  my %args = @_;
  my $newcgi = new CGI ("");
  $newcgi->param ($_, $args{$_}) for keys %args;
  return $newcgi->self_url(-full=>0, -relative=>1, -path_info=>0);
}

sub urlroot
{
  my %args = @_;
  my $path = $ENV{SCRIPT_NAME};
  $path =~ s,/[^/]*$,,;
  return $path;
}
