#! /usr/bin/env perl

##H Activate blocks when file-level information is needed again.
##H
##H Files belong to blocks; when the file replicas are no longer needed
##H they are collapsed to block replicas, which remember entire sets of
##H files.  When the files in the blocks are needed again, for instance
##H because subscriptions need to be activated again, this agent expands
##H the block replicas back into file replicas.
##H
##H Usage:
##H   BlockActivate
##H      -state DIRECTORY -node NAME -db FILE[:SECTION] [-wait SECS]
##H
##H -state     agent state directory
##H -node      the node where this agent runs
##H -db        database connection configuration parameter file
##H -wait      time to wait in seconds between work scans

BEGIN {
  use warnings; use strict;
  our $me = $0; $me =~ s|.*/||;
  our $home = $0; $home =~ s|/[^/]+$||; $home ||= "."; $home .= "/../../Toolkit/Common";
  unshift(@INC, $home);
}

######################################################################
use UtilsHelp;
use Getopt::Long;
my %args = (WAITTIME => 60);
&GetOptions ("state=s"		=> \$args{DROPDIR},
	     "node=s"           => \$args{MYNODE},
	     "db=s"	        => \$args{DBCONFIG},
	     "wait=f"		=> \$args{WAITTIME},
	     "help|h"		=> sub { &usage() });

if (@ARGV || !$args{DROPDIR} || !$args{DBCONFIG})
{
    die "Insufficient parameters, use -h for help.\n";
}

my $agent = new BlockDeactivate (%args);
$SIG{INT} = sub { system "touch $agent->{STOPFLAG}"; $agent->maybeStop() };
$SIG{QUIT} = sub { system "touch $agent->{STOPFLAG}"; $agent->maybeStop() };
$SIG{TERM} = sub { system "touch $agent->{STOPFLAG}"; $agent->maybeStop() };
$agent->process();

################################################
package BlockDeactivate; use strict; use warnings; use base 'UtilsAgent';
use File::Path;
use Data::Dumper;
use UtilsCommand;
use UtilsLogging;
use UtilsTiming;
use UtilsCatalogue;
use UtilsDB;
use DBI;

sub new
{
    my $proto = shift;
    my $class = ref($proto) || $proto;
    my $self = $class->SUPER::new(@_);
    my %params = (DBCONFIG => undef,		# Database configuration file
	  	  AGENTID => "BlockDeactivate");      # Identity for activity logs

    my %args = (@_);
    map { $self->{$_} = $args{$_} || $params{$_} } keys %params;
    bless $self, $class;
    return $self;
}


# Pick up work from the database and start site specific scripts if necessary
sub idle
{
    my ($self, @pending) = @_;
    my $dbh = undef;
    my @collectionsWanted = ();

    eval
    {
	$dbh = &connectToDatabase ($self) or die "failed to connect";
	
	# look for newly requested collections and make the files available in t_replica_state
	@collectionsWanted = $self->getGroupsWanted($dbh);
	if (scalar (@collectionsWanted) !=0) {
	    # make those collections available in t_replica_state if necessary
	    foreach my $collection (@collectionsWanted) {
		$self->makeAvailInTMDB($dbh, $collection);
	    }
	}
	
	# final commit
	$dbh->commit();
    };
    do { &alert ("database error: $@"); $dbh->rollback if $dbh } if $@;

    # Disconnect from the database
    &disconnectFromDatabase ($self, $dbh);

    # Have a little nap
    $self->nap ($self->{WAITTIME});
}


sub getGroupsWanted {
    my ($self, $dbh) = @_; 
    my @packet = ();
    
# any collections wanted, which are not in t_replica_state ? Let's check....    
# FIXME: really ugly SQL... I am wondering if this could be improved
    my $h_packet = &dbexec ($dbh, qq{
	select ts.dataset, ts.owner, ts.destination
        from t_subscription ts, t_file tf, t_block tb
        where tf.inblock=tb.name and 
        ts.dataset=tb.dataset and 
        ts.owner=tb.owner and 
        tf.guid not in (select guid from t_replica_state)});
    
    while (my ($owner, $dataset, $node) = $h_packet->fetchrow_array){
	push (@packet, "$dataset:$owner:$node")
	    if ! grep(/"$dataset:$owner:$node"/,@packet);
    }
# return those dataset owner pairs
    return @packet;
    
}


sub makeAvailInTMDB {
    my ($self, $dbh, $collection) = @_;
    my ($dataset, $owner, $node) = split(':',$collection);
    
    my $now = time();
# we need the guids for the files belonging to the selected dataset-owner pairs
    my @guids = &getGUIDs($dbh, $dataset, $owner);
    
    foreach my $guid (@guids) {
# let's check, if the guids are already in t_replica state and add them if they are not
	my $guid_exists = &dbexec($dbh, qq{
	    select count(*) from t_replica_state
	    where node=:node and guid=:guid},
	    ":node"=>$node, ":guid"=>$guid);

	&dbexec($dbh, qq{
	    insert into t_replica_state (timestamp,guid,node,state,state_timestamp)
      	    values ("$now","$guid","$node",'0',"$now")}) if !$guid_exists;

	$dbh->commit();
    }
}

sub getGUIDs {
    my ($dbh, $dataset, $owner) = @_;
    my @guids = ();

    my $guids_h = &dbexec ($dbh, qq{
	select f.guid from t_dsb_fileid f, t_dsb_dataset d
	where  d.dataset=:dataset and d.owner=:owner and d.id=f.id},
	":dataset"=>$dataset, ":owner"=>$owner);
    
    while (my ($guid) = $guids_h->fetchrow() ) {
	push (@guids, $guid);
    }
    return @guids;
}
