#! /usr/bin/env perl

##H Trigger DLS update once blocks were completely transferred.
##H
##H The BlockMonitor agent periodically updates the transfer progress
##H of various blocks.  Once a block has been transferred completely,
##H this agent triggers an update of the DLS.
##H
##H Usage:
##H   BlockDLSUpdate -state DIRECTORY -db FILE[:SECTION]
##H
##H -state     agent state directory
##H -db        database connection configuration parameter file
##H -log       where to redirect logging information

BEGIN {
  use warnings; use strict; $^W=1;
  our $me = $0; $me =~ s|.*/||;
  our $home = $0; $home =~ s|/[^/]+$||; $home ||= "."; $home .= "/../../Toolkit/Common";
  unshift(@INC, $home);
}


######################################################################
my %args;
use Getopt::Long;
use PHEDEX::Core::Help;
use PHEDEX::BlockConsistency::Core;
use PHEDEX::BlockDLSUpdate::Agent;

&GetOptions ("state=s"     => \$args{DROPDIR},
             "db=s"        => \$args{DBCONFIG},
             "label=s"     => \$args{LABEL},
	     "log=s"       => \$args{LOGFILE},
	     "help|h"      => sub { &usage() });

(new BlockDLSUpdate (%args,@ARGV))->process();
