package PHEDEX::File::Download::Circuits::Helpers::HTTP::HttpConstants;

use warnings;
use strict;

use base 'Exporter';

our @EXPORT = qw(HTTP_CLIENT_NOT_SPAWNED HTTP_CLIENT_INVALID_PARAMS HTTP_CLIENT_INVALID_REQUEST

                 HTTP_SERVER_ALREADY_STARTED HTTP_SERVER_NOT_STARTED
                 HTTP_SERVER_HANDLER_INVALID_PARAMS HTTP_SERVER_HANDLER_INVALID_URI HTTP_SERVER_HANDLER_ALREADY_EXISTS HTTP_SERVER_HANDLER_INVALID_PARAMS
                 HTTP_SERVER_HANDLER_NOT_FOUND

                 HTTP_SERVER_REQUEST_INVALID HTTP_SERVER_REQUEST_INVALID_FORMAT HTTP_SERVER_REQUEST_NO_ARGS
                 );

use constant {
    HTTP_CLIENT_NOT_SPAWNED             =>  1,
    HTTP_CLIENT_INVALID_PARAMS          =>  2,
    HTTP_CLIENT_INVALID_REQUEST         =>  3,

    HTTP_SERVER_ALREADY_STARTED         => 20,
    HTTP_SERVER_NOT_STARTED             => 21,

    HTTP_SERVER_HANDLER_INVALID_PARAMS  => 22,
    HTTP_SERVER_HANDLER_INVALID_URI     => 23,
    HTTP_SERVER_HANDLER_ALREADY_EXISTS  => 24,
    HTTP_SERVER_HANDLER_NOT_FOUND       => 25,

    HTTP_SERVER_REQUEST_INVALID         => 26,
    HTTP_SERVER_REQUEST_INVALID_FORMAT  => 27,

    HTTP_SERVER_REQUEST_NO_ARGS         => 28,
};

1;

