delete from t_routing where to_node like 'Test-FCL-%'
delete from t_routing where from_node like 'Test-FCL-%'
delete from t_routing where gateway like 'Test-FCL-%'
delete from t_agent_status where node like 'Test-FCL-%'
delete from t_node_neighbour where node like 'Test-FCL-%'
delete from t_node where name like 'Test-FCL-%'
insert into t_node values ('Test-FCL-A')
insert into t_node values ('Test-FCL-B')
insert into t_node values ('Test-FCL-C')
insert into t_node values ('Test-FCL-D')
insert into t_node values ('Test-FCL-E')
insert into t_node values ('Test-FCL-F')
insert into t_node values ('Test-FCL-A-MSS')
insert into t_node values ('Test-FCL-B-MSS')
insert into t_node values ('Test-FCL-C-MSS')
insert into t_node values ('Test-FCL-D-MSS')
insert into t_node values ('Test-FCL-E-MSS')
insert into t_node values ('Test-FCL-F-MSS')
insert into t_node_neighbour values ('Test-FCL-A','Test-FCL-B',1)
insert into t_node_neighbour values ('Test-FCL-A','Test-FCL-C',1)
insert into t_node_neighbour values ('Test-FCL-A','Test-FCL-D',1)
insert into t_node_neighbour values ('Test-FCL-A','Test-FCL-E',1)
insert into t_node_neighbour values ('Test-FCL-A','Test-FCL-F',1)
insert into t_node_neighbour values ('Test-FCL-B','Test-FCL-A',1)
insert into t_node_neighbour values ('Test-FCL-B','Test-FCL-C',1)
insert into t_node_neighbour values ('Test-FCL-B','Test-FCL-D',1)
insert into t_node_neighbour values ('Test-FCL-B','Test-FCL-E',1)
insert into t_node_neighbour values ('Test-FCL-B','Test-FCL-F',1)
insert into t_node_neighbour values ('Test-FCL-C','Test-FCL-A',1)
insert into t_node_neighbour values ('Test-FCL-C','Test-FCL-B',1)
insert into t_node_neighbour values ('Test-FCL-C','Test-FCL-D',1)
insert into t_node_neighbour values ('Test-FCL-C','Test-FCL-E',1)
insert into t_node_neighbour values ('Test-FCL-C','Test-FCL-F',1)
insert into t_node_neighbour values ('Test-FCL-D','Test-FCL-A',1)
insert into t_node_neighbour values ('Test-FCL-D','Test-FCL-B',1)
insert into t_node_neighbour values ('Test-FCL-D','Test-FCL-C',1)
insert into t_node_neighbour values ('Test-FCL-D','Test-FCL-E',1)
insert into t_node_neighbour values ('Test-FCL-D','Test-FCL-F',1)
insert into t_node_neighbour values ('Test-FCL-E','Test-FCL-A',1)
insert into t_node_neighbour values ('Test-FCL-E','Test-FCL-B',1)
insert into t_node_neighbour values ('Test-FCL-E','Test-FCL-C',1)
insert into t_node_neighbour values ('Test-FCL-E','Test-FCL-D',1)
insert into t_node_neighbour values ('Test-FCL-E','Test-FCL-F',1)
insert into t_node_neighbour values ('Test-FCL-F','Test-FCL-A',1)
insert into t_node_neighbour values ('Test-FCL-F','Test-FCL-B',1)
insert into t_node_neighbour values ('Test-FCL-F','Test-FCL-C',1)
insert into t_node_neighbour values ('Test-FCL-F','Test-FCL-D',1)
insert into t_node_neighbour values ('Test-FCL-F','Test-FCL-E',1)
insert into t_node_neighbour values ('Test-FCL-A','Test-FCL-A-MSS',1)
insert into t_node_neighbour values ('Test-FCL-A-MSS','Test-FCL-A',1)
insert into t_node_neighbour values ('Test-FCL-B','Test-FCL-B-MSS',1)
insert into t_node_neighbour values ('Test-FCL-B-MSS','Test-FCL-B',1)
insert into t_node_neighbour values ('Test-FCL-C','Test-FCL-C-MSS',1)
insert into t_node_neighbour values ('Test-FCL-C-MSS','Test-FCL-C',1)
insert into t_node_neighbour values ('Test-FCL-D','Test-FCL-D-MSS',1)
insert into t_node_neighbour values ('Test-FCL-D-MSS','Test-FCL-D',1)
insert into t_node_neighbour values ('Test-FCL-E','Test-FCL-E-MSS',1)
insert into t_node_neighbour values ('Test-FCL-E-MSS','Test-FCL-E',1)
insert into t_node_neighbour values ('Test-FCL-F','Test-FCL-F-MSS',1)
insert into t_node_neighbour values ('Test-FCL-F-MSS','Test-FCL-F',1)
