#!/usr/bin/perl

##H Checks the status of transfer request drops.
##H
##H Usage: TRFileCheck /drop/box/area database table [drop...]
##H
##H /drop/box/area should be the directory containing the state
##H directories for the drop box agents, so the script can check
##H which drops are still being processed ("pending")
##H
##H database should be the name of the tmdb oracle database, and
##H table should be the name of the file table (filesfortransfer
##H for v1, t_files_for_transfer for v2).
##H
##H The rest of the arguments are expected to be "drop" directories.
##H This tool reads the XML catalogue fragments from the drops, gets
##H the list of the GUIDs, and compares both with the tmdb database
##H and the drop box area to evaluate the status of the drop.
##H
##H For each drop, a line is printed out with the name of the drop,
##H the number of files found in the catalogue, the number of guids
##H already registered in tmdb, and two flags, "TRANSFERRED" and/or
##H "PENDING".  The former indicates that all the files were found
##H in tmdb, the second indicates there is still a drop in the disk
##H queues.

BEGIN { use strict; use warnings;
  my $me = $0; $me =~ s|.*/||;
  my $home = $0; $home =~ s|/[^/]+$||; $home ||= ".";
  unshift(@INC, $home); }
use UtilsTR;

my $mouth = shift (@ARGV);
my $db = shift (@ARGV);
my $table = shift (@ARGV);
foreach my $drop (@ARGV)
{
    my $result = &checkAssignmentFiles ($mouth, $db, $table, $drop);
    my $info = $result->{$drop};
    next if ! defined $info; # FIXME: warn/whine?

    # Print stats line
    my $pending  = $info->{IS_PENDING_TRANSFER} ? " PENDING" : "";
    my $transfer = $info->{IS_FULLY_TRANSFERRED} ? " TRANSFERRED" : "";
    my $onmss    = $info->{IS_FULLY_IN_MSS} ? " AVAILABLE" : "";
    print "$drop FILES $info->{N_FILES}",
          " MSS $info->{N_IN_MSS}",
	  " INTMDB $info->{N_TRANSFERRED}",
	  "$onmss$pending$transfer\n";
}
