#!/usr/bin/env perl

##H Record contact information for the transfer request.
##H
##H Usage: TRNewContact [-r] REQUEST [INFO...]
##H
##H REQUEST is the request directory previously created with TRNew.
##H Adds all the INFO as the contact details of this request; if "-r"
##H option is used, cancels previous contact details.  The contacts
##H are not really used for anything at this time, but usually they
##H are the e-mail addresses of the requestors.
##H
##H This program updates the transfer request ticket.

BEGIN {
  use strict; use warnings; $^W=1;
  our $me = $0; $me =~ s|.*/||;
  our $home = $0; $home =~ s|/[^/]+$||; $home ||= "."; $home .= "/../../Toolkit/Common";
  unshift(@INC, $home);
}

my $now = time();
my $reset = 0;
use Getopt::Long;
use UtilsHelp;
use UtilsNet;
use Cwd;
&GetOptions ("r"           => \$reset,
	     "help|h"      => sub { &usage() });

my $request = shift (@ARGV);
if (!$request || ! -f $request)
{
    die "Incorrect parameters, use -h for help.\n";
}

-f "$request" or die "$request: not a transfer request\n";

# Append to the ticket
(open (TICKET, ">> $request")
 && print(TICKET "$now CMD $me @{[scalar getpwuid($<)]}\@@{[&getfullhostname()]}\n")
 && (! $reset || print(TICKET "$now CANCEL CONTACT\n"))
 && (print(TICKET "$now CONTACT @ARGV\n"))
 && close (TICKET))
    or die "$request: cannot update ticket: $!\n";
