#!/usr/bin/env perl

##H Set the database context for the transfer request.
##H
##H Usage: TRNewDatabase [-r] REQUEST [DATABASE...]
##H
##H REQUEST is the request directory previously created with TRNew.
##H Adds all the DATABASEs as the context of this request; if "-r"
##H option is used, cancels previous database assignments.  Note
##H that the database context is purely for information only at
##H this time -- it is not respected by any of the other tools.
##H
##H This program updates the transfer request ticket.

BEGIN {
  use strict; use warnings; $^W=1;
  our $me = $0; $me =~ s|.*/||;
  our $home = $0; $home =~ s|/[^/]+$||; $home ||= "."; $home .= "/../../Toolkit/Common";
  unshift(@INC, $home);
}

my $now = time();
my $reset = 0;
use Getopt::Long;
use UtilsHelp;
use UtilsNet;
use Cwd;
&GetOptions ("r"           => \$reset,
	     "help|h"      => sub { &usage() });

my $request = shift (@ARGV);
if (!$request || ! -f $request)
{
    die "Incorrect parameters, use -h for help.\n";
}

-f "$request" or die "$request: not a transfer request\n";

# Append to the ticket
(open (TICKET, ">> $request")
 && print(TICKET "$now CMD $me @{[scalar getpwuid($<)]}\@@{[&getfullhostname()]}\n")
 && (! $reset || print(TICKET "$now CANCEL DATABASE\n"))
 && (print(TICKET "$now DATABASE @ARGV\n"))
 && close (TICKET))
    or die "$request: cannot update ticket: $!\n";
