#!/bin/bash
DBS3CLIENTVERSION=3.1.1a
DBS3CLIENT=cms+dbs3-client+$DBS3CLIENTVERSION
  
DATAPROVIDERVERSION=1.0.5p
DATAPROVIDER=cms+lifecycle-dataprovider+$DATAPROVIDERVERSION
  
LIFECYCLEAGENTVERSION=1.1.0
LIFECYCLEAGENT=cms+PHEDEX-lifecycle+$LIFECYCLEAGENTVERSION
    
DBS3LIFECYCLEVERSION=0.0.4p
DBS3LIFECYCLE=cms+dbs3-lifecycle+$DBS3LIFECYCLEVERSION

WORKINGDIR=/data
SCRAM_ARCH=slc5_amd64_gcc461
REPO=comp.pre.giffels
SWAREA=$WORKINGDIR/sw/$REPO
