#!/usr/bin/env perl

##H Generate Oracle SQL*Plus connect identifier from DBParam file.
##H
##H Usage:
##H   OracleConnectId -db FILE[:SECTION]

BEGIN {
  use strict; use warnings; $^W=1;
  our $me = $0; $me =~ s|.*/||;
  our $home = $0; $home =~ s|/[^/]+$||; $home ||= "."; $home .= "/../Toolkit/Common";
  unshift(@INC, $home);
}
use UtilsDB;

# Process command line arguments.
my %args = ();
while (scalar @ARGV)
{
    if ($ARGV[0] eq '-db' && scalar @ARGV > 1)
    { shift (@ARGV); $args{DBCONFIG} = shift(@ARGV); }
    elsif ($ARGV[0] eq '-h')
    { &usage(); }
    else
    { last; }
}


# Check arguments.
if (@ARGV || !$args{DBCONFIG})
{
    die "Insufficient parameters, use -h for help.\n";
}

&parseDatabaseInfo (\%args);
print "$args{DBH_DBUSER}/$args{DBH_DBPASS}\@$args{DBH_DBNAME}\n";
