#!/usr/bin/env perl

##H Generate Oracle SQL*Plus connect identifier from DBParam file.
##H
##H Usage:
##H   OracleConnectId -db FILE[:SECTION]

BEGIN {
  use strict; use warnings; $^W=1;
  our $me = $0; $me =~ s|.*/||;
  our $home = $0; $home =~ s|/[^/]+$||; $home ||= "."; $home .= "/../Toolkit/Common";
  unshift(@INC, $home);
}

# Process command line arguments.
my %args;
use Getopt::Long;
use UtilsHelp;
use UtilsDB;
&GetOptions ("db=s"        => \$args{DBCONFIG},
	     "help|h"      => sub { &usage() });

# Check arguments.
if (@ARGV || !$args{DBCONFIG})
{
    die "Insufficient parameters, use -h for help.\n";
}

&parseDatabaseInfo (\%args);
print "$args{DBH_DBUSER}/$args{DBH_DBPASS}\@$args{DBH_DBNAME}\n";
