#!/usr/bin/env python
"""
_DBSDelete_
                                                                                
Command line tool to delete a block.

"""
from DBSAPI.dbsApi import DbsApi
from DBSAPI.dbsOptions import DbsOptionParser

import string,sys,os

def delete(url,lblock):
  args = {'url' : url}
  dbsapi = DbsApi(args)

  if (lblock != None):
    blockList=lblock.split(',')
    for block in blockList:
      block_objects = dbsapi.listBlocks(block_name=block)
      dbsblock = 0
      if len(block_objects):
        dbsblock = block_objects.pop(0)
      if dbsblock:
        # TODO:  is dataset required?
        print "throwing away %" % dbsblock        
        dbsapi.deleteBlock(dataset=dbsblock['Dataset'], block=dbsblock)
        print "deleting %" % dbsblock        
        dbsapi.deleteRecycleBin(dataset=dbsblock['Dataset'], block=dbsblock)
      else:
        raise Exception("block='%s' not found in dbs='%s'" % (block, url))

  return

def main ():
  from optparse import OptionParser

  usage="""\npython DBSDelete [options]"""
  parser = OptionParser(usage=usage)

  parser.add_option('-u', '--url', dest='url', default='https://cmsdbsprod.cern.ch:8443/cms_dbs_prod_global_writer/servlet/DBSServlet', help='DBS URL')
  parser.add_option('-b', '--block', dest='block', default=None, help='Block to be invalidated')

  (opts, args) = parser.parse_args()

  if opts.url == None:
    print "--url option not provided."
    print "Using %s"%opts.url

  if opts.block == None:
    print "\n --block option has to be provided"
    print usage
    sys.exit(1)

  try:
    if opts.block != None:
      delete(opts.url, opts.block)
  except Exception, ex:
    print "Caught exception: %s" % str(ex)
    sys.exit(1)

  sys.exit(0)

if __name__ == "__main__":
  main()
