#!/usr/bin/env python
"""
_DBSInjectReport_
                                                                                
Command line tool to list blocks from DBS given a block.

"""
import dbsCgiApi
from dbsException import DbsException

import string,sys,os,getopt,time

#usage="\n Usage: DBSGetBlocks.py <options> \n Options: \n --DBSAddress=<MCLocal/Writer> \t\t DBS database instance \n --DBSURL=<URL> \t\t DBS URL \n --dataset=<DATASET> \t\t DBS Block Name \n "
valid = ['DBSAddress=','DBSURL=','DATASET=']
try:
    opts, args = getopt.getopt(sys.argv[1:], "", valid)
except getopt.GetoptError, ex:
#    print usage
    print str(ex)
    sys.exit(1)

url = "http://cmsdoc.cern.ch/cms/test/aprom/DBS/CGIServer/prodquery"
dbinstance = None
datasetName = None

our_List_of_Blocks = [] 
our_Dic_of_a_Block = {} 
our_List = ""

for opt, arg in opts:
    if opt == "--DBSAddress":
        dbinstance = arg
    if opt == "--DBSURL":
        url = arg
    if opt == "--DATASET":
        datasetName = arg

if dbinstance == None:
#    print "--DBSAddress option not provided. For example : --DBSAddress MCLocal/Writer"
#    print usage
    sys.exit(1)


#print ">>>>> DBS URL : %s DBS Address : %s"%(url,dbinstance)
#  //
# // Get API to DBS
#//
## database instance
args = {'instance' : dbinstance}
dbsapi = dbsCgiApi.DbsCgiApi(url, args)

#  //
# // Getting Blocks
#//

def listBlocksDBS(datasetName):

#    print "Geting LFNs  from block/dataset "
    return dbsapi.getDatasetFileBlocks (datasetName) 

if (datasetName != None) :
  our_List_of_Blocks = listBlocksDBS(datasetName)
  for item in our_List_of_Blocks:
     our_Dic_of_a_Block = item
     our_List+=our_Dic_of_a_Block['blockName']+","  
  our_List = our_List[:-1]
  print our_List
