#!/bin/sh

##H Check whether to bypass the file download.
##H
##H Usage: FileDownloadBypass [-t] FROM-PFN TO-PFN
##H
##H This is used by the file download agent to determine whether we
##H can safely bypass the file transfer and proceed to publish the
##H file.  This happens when the TV_LCG_Production virtual node has
##H files registered for my site, but we don't know about them yet.
##H
##H If the file copy is safe to bypass, print out the destination
##H PFN to use instead.  Typically this is the source file, though
##H one could use something else as well.
##H
##H To proceed with normal copy, print out nothing.  The exit code
##H from this script is ignored.
##H
##H If "-t" option is given, goes into test mode, passing random
##H files through.

do_test=false
while [ $# -ge 1 ]; do
  case $1 in
    -t ) do_test=true; shift ;;
    -* ) echo "unrecognised option $1" 1>&2; exit 5 ;;
    *  ) break ;;
  esac
done

from="$1" to="$2"

if ! $do_test; then
  case $from in
    # Skip when the same file or from my own site
    *://castorgrid*.cern.ch:*/castor/cern.ch/* | \
    *://castorgrid*.cern.ch/castor/cern.ch/* | \
    $to )
      echo $from;;
  esac
elif [ $(expr $RANDOM % 10) -le 4 ]; then
  echo $from # $to
fi

exit 0
