#!/bin/sh

# Pick up arguments
reason="$1" pfn="$2"

# Handle removal.  We remove destination both before transfer and
# after a failed transfer.
case $reason in
  pre | post )
   srm-advisory-delete -retry_num=1 "$pfn" 2>/dev/null
   ;;
  * ) echo "unrecognised reason to remove $pfn: $reason" 1>&2; exit 1;;
esac

exit 0
