#!/bin/sh

for f in /etc/profile.d/*.sh; do . $f; done

[ $# = 1 ] || { echo "usage: $0 CERT-DIRECTORY" 1>&2; exit 1; }

dir="$1"
[ -d "$dir" ] ||
  { echo "$dir: no such certificate directory" 1>&2; exit 2; }
cd "$dir" ||
  { echo "$dir: cannot change to directory" 1>&2; exit 3; }
[ -f hostcert.pem -a -f hostkey.pem ] ||
  { echo "$dir: no hostcert.pem/hostkey.pem/proxy.cert here" 1>&2; exit 4; }

export MYPROXY_SERVER=myproxy.cern.ch
export X509_USER_CERT=$PWD/hostcert.pem
export X509_USER_KEY=$PWD/hostkey.pem
unset X509_USER_PROXY

# If there is a new user proxy here, replace the proxy.cert with it.
uproxy=$(ls -t x509up_* 2>/dev/null | head -1)
if [ ! -z "$uproxy" -a -f "$uproxy" ]; then
  rm -f proxy.cert
  cp "$uproxy" proxy.cert
  chmod 600 proxy.cert
  rm -f "$uproxy"
fi

# Check if the proxy is still valid for at least 24 hours; if so, quit
grid-proxy-info -file proxy.cert -exists -valid 24:00 && exit 0

# Try to renew the proxy
myproxy-get-delegation -t 36 -l phedex -a proxy.cert -o proxy.cert.new > /dev/null ||
  { echo "myproxy-get-delegation failed: $?" 1>&2; exit 5; }

# Check the validity of the new proxy.  It should be valid for 12 hours.
# If it's valid, move it into place, otherwise check how much is left
# and warn the caller; however leave the old proxy in place in case it
# still works and this is a transient error.
if grid-proxy-info -file proxy.cert.new -exists -valid 11:00; then
   mv -f proxy.cert.new proxy.cert
else
   timeleft=$(grid-proxy-info -file proxy.cert.new -timeleft)
   echo "$0: failed to renew proxy in $dir, $timeleft seconds left" 1>&2
   rm -f proxy.cert.new
   exit 6
fi

exit 0
