#!/usr/bin/env perl

# Create fake catalogues and checksum information for test files
# for the LCG Service Challenge 2.

$dirbase = "srm://radiantservice.cern.ch:8443/castor/cern.ch/grid/dteam/storage/transfer-test";
$lfnpat = "sample-file-1gig-%02d.dat";
$nfiles = 40;
$size = 1048576000;
$dups = shift(@ARGV) || 43200;

open (XML, "> XMLCatFragment.xml") or die "XMLCatFragment.xml: $!\n";
open (CKSUM, "> Checksum.txt") or die "Checksum.txt: $!\n";

print XML <<EOF;
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE POOLFILECATALOG SYSTEM "InMemory">
<POOLFILECATALOG>
  <META name="Content" type="string"/>
  <META name="DBoid" type="string"/>
  <META name="DataType" type="string"/>
  <META name="FileCategory" type="string"/>
  <META name="Flags" type="string"/>
  <META name="dataset" type="string"/>
  <META name="jobid" type="string"/>
  <META name="owner" type="string"/>
  <META name="runid" type="string"/>
EOF

for (my $dup = 0; $dup < $dups; ++$dup)
{
    for (my $i = 0; $i < $nfiles; ++$i)
    {
	my $uuid = qx(uuidgen); chomp ($uuid); $uuid =~ y/[a-z]/[A-Z]/;
	my $lfn = sprintf ($lfnpat, $i);
	my $pfn = "$dirbase/$lfn";

	print CKSUM "-1 $size $lfn\n" if ! exists $cksumdone{$lfn};
	$cksumdone{$lfn} = 1;
	print XML <<EOF;
  <File ID="$uuid">
    <physical>
      <pfn filetype="ROOT_All" name="$pfn"/>
    </physical>
    <logical>
      <lfn name="$lfn"/>
    </logical>
    <metadata att_name="Content" att_value=""/>
    <metadata att_name="DBoid" att_value="SC2_FAKE"/>
    <metadata att_name="DataType" att_value="SC2_FAKE"/>
    <metadata att_name="FileCategory" att_value="SC2_FAKE"/>
    <metadata att_name="Flags" att_value=""/>
    <metadata att_name="dataset" att_value="SC2"/>
    <metadata att_name="jobid" att_value="$dup"/>
    <metadata att_name="owner" att_value="SC2"/>
    <metadata att_name="runid" att_value="$i"/>
  </File>
EOF
    }
}
print XML "</POOLFILECATALOG>\n";

close (XML);
close (CKSUM);
